name: Build LaTeX PDF

on:
  push:
    paths:
      - '**.tex'
  pull_request:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v4
        with:
            texlive_version: 2024
            root_file: logbook.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: logbook-pdf
          path: logbook.pdf
